services:
  web_app:
    # 使用微软官方的 .NET SDK 镜像
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      # 将工程目录映射到容器内的 /src 中
      - .:/src
      # 容器内的这两个目录不应该影响宿主系统, 因为这些是编译器的缓存
      - /src/bin
      - /src/obj
    ports:
      # 将宿主系统的 80 端口与容器实例的 3000 端口绑定
      - 80:3000
    environment:
      # 设置环境变量, 用于访问 MongoDB 容器实例
      # 注意 mongo_db 这个名字在下面有定义
      MONGODB_URI: mongodb://mongo_db:27017/
    # 将容器实例内的 /src 路径设置为工作路径
    working_dir: /src
    # 容器实例启动时在工作路径执行命令
    command: dotnet run

  mongo_db:
    # 使用 MongoDB 官方镜像
    image: mongo
    volumes:
      # 将宿主系统中名为 mongo_data_db 的 volume 映射到容器的 /data/db 路径中
      # mongo_db 所存储的数据应该被映射到容器外部, 这样才能持久化存储
      - mongo_data_db:/data/db
      # 将宿主系统中名为 mongo_config_db 的 volume 映射到容器的 /data/configdb 路径中
      - mongo_config_db:/data/configdb

volumes:
  # 在宿主系统中创建名为 mongo_data_db 的 volume, 存放数据库的数据
  mongo_data_db: {}
  # 在宿主系统中创建名为 mongo_config_db 的 volume, 存放数据库的配置
  mongo_config_db: {}

# 不需要设置 network, 因为会自动创建
# networks:
