# 此文件用于部署, 开发时请使用工程根目录的 compose.yaml

services:
  web-app-demo:
    # 使用已经上传 Docker Hub 中的镜像
    image: whisperpine/web-app-demo:latest
    # 如果意外停止则自动重启
    restart: always
    ports:
      # 将宿主系统的 80 端口与容器实例的 3000 端口绑定
      - 80:3000
    depends_on:
      # 让 mongo 在 up 时更早启动, down 时更晚关闭
      - mongo
    environment:
      # 设置环境变量, 用于访问 MongoDB 容器实例 (注意 mongo 这个名字在下面有定义)
      MONGODB_URI: mongodb://mongo:27017/
      # 设置环境变量, 用于指定应用程序所读写的 database 名称
      DB_NAME: web-app-demo

  mongo:
    # 使用 MongoDB 官方镜像
    image: mongo:7.0
    # 如果意外停止则自动重启
    restart: always
    volumes:
      # 将宿主系统中名为 mongo-data-db 的 volume 映射到容器的 /data/db 路径中
      # mongo 所存储的数据应该被映射到容器外部, 这样才能持久化存储
      - mongo-data-db:/data/db
      # 将宿主系统中名为 mongo-config-db 的 volume 映射到容器的 /data/configdb 路径中
      - mongo-config-db:/data/configdb

volumes:
  # 在宿主系统中创建名为 mongo-data-db 的 volume, 存放数据库的数据
  mongo-data-db: {}
  # 在宿主系统中创建名为 mongo-config-db 的 volume, 存放数据库的配置
  mongo-config-db: {}

# 不需要设置 network, 因为会自动创建
# networks:
