# 此文件用于部署, 开发时请使用工程根目录的 compose.yaml

services:
  web_app:
    # 使用已经上传 Docker Hub 中的镜像
    image: whisperpine/web_app:0.1
    # 如果意外停止则自动重启
    restart: always
    ports:
      # 将宿主系统的 80 端口与容器实例的 3000 端口绑定
      - 80:3000
    environment:
      # 设置环境变量, 用于访问 MongoDB 容器实例
      MONGODB_URI: mongodb://mongo_db:27017/
    # 将容器实例内的 /publish 路径设置为工作路径
    working_dir: /publish
    # 容器实例启动时在工作路径执行命令
    command: dotnet WebApp.dll

  mongo_db:
    # 使用 MongoDB 官方镜像
    image: mongo
    # 如果意外停止则自动重启
    restart: always
    volumes:
      # 将宿主系统中名为 mongo_data_db 的 volume 映射到容器的 /data/db 路径中
      # mongo_db 所存储的数据应该被映射到容器外部, 这样才能持久化存储
      - mongo_data_db:/data/db
      # 将宿主系统中名为 mongo_config_db 的 volume 映射到容器的 /data/configdb 路径中
      - mongo_config_db:/data/configdb

volumes:
  # 在宿主系统中创建名为 mongo_data_db 的 volume, 存放数据库的数据
  mongo_data_db: {}
  # 在宿主系统中创建名为 mongo_config_db 的 volume, 存放数据库的配置
  mongo_config_db: {}
